name: nhost_flutter_graphql
description: >
  Provides GraphQL clients to your Flutter application, automatically configured
  to work with Nhost
version: 2.1.0
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_flutter_graphql
issue_tracker: https://github.com/nhost/nhost-dart/issues

publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.0
  logging: ^1.0.1

  # Nhost packages
  nhost_sdk: #^3.0.4
    path: ../nhost_sdk
  nhost_flutter_auth: #^2.0.4
    path: ../nhost_flutter_auth
  nhost_graphql_adapter: #^2.0.4
    path: ../nhost_graphql_adapter
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.0
  mockito: ^5.0.2
