name: nhost_gql_links
version: 2.0.4
description: Constructs GraphQL links for use with graphql and ferry packages
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_gql_links
issue_tracker: https://github.com/nhost/nhost-dart/issues

publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  gql_exec: 0.4.1
  gql_http_link: 0.4.4+1
  gql_link: ^0.5.0
  gql_websocket_link: ^0.3.4
  gql: ^0.14.0
  http: ^0.13.5
  logging: any #^1.0.1
  meta: any #^1.3.0
  web_socket_channel: any #^2.0.0

  # Nhost packages
  nhost_sdk: #^3.0.4
    path: ../nhost_sdk
dev_dependencies:
  async: any #^2.5.0
  fake_async: any #^1.2.0
  lints: any #^1.0.0
  mockito: any #^5.0.2
  nock: 1.1.3
  stream_channel: any #^2.1.0
  test: ^1.18.0
